### ISSUE TITLE
Possible to add low battery notifications?

### ISSUE THREAD

**Issue by montanaishome** [techyowl/homebridge-august-smart-locks#16]
Is there any way to expose the battery level on the lock to HomeKit?  See this comment on Reddit: https://www.reddit.com/r/homebridge/comments/jr054y/show_august_battery_level/gbsraao/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3

**Comment by dxdc** [comment]
Maybe simpler to bind to the door contact sensor using `StatusLowBattery`?

```
/**
 * Service "Contact Sensor"
 */

export class ContactSensor extends Service {

  static UUID: string = '00000080-0000-1000-8000-0026BB765291';

  constructor(displayName?: string, subtype?: string) {
    super(displayName, ContactSensor.UUID, subtype);

    // Required Characteristics
    this.addCharacteristic(Characteristic.ContactSensorState);

    // Optional Characteristics
    this.addOptionalCharacteristic(Characteristic.StatusActive);
    this.addOptionalCharacteristic(Characteristic.StatusFault);
    this.addOptionalCharacteristic(Characteristic.StatusTampered);
    this.addOptionalCharacteristic(Characteristic.StatusLowBattery);
    this.addOptionalCharacteristic(Characteristic.Name);
  }
}
```

**Comment by dxdc** [comment]
I think either a separate query (or replacement query) may be required for checking battery. From some initial inspection of the various returned values, we need something like this:

- https://github.com/snjoetw/py-august/blob/master/tests/fixtures/get_lock.online.json
- https://github.com/snjoetw/py-august/blob/master/tests/fixtures/get_lock.online_with_doorsense.json

In this case, `battery` is reported as a decimal value (0-1). With this value, it would be simple enough to update a battery setting, e.g., using a setting of 0.25:

```
doorService.getCharacteristic(self.Characteristic.StatusLowBattery).updateValue(accessory.context.batteryRaw > 0.25 ? 0 : 1);
```

However, this is quite different than the standard values that are being retrieved:

- https://github.com/snjoetw/py-august/blob/master/tests/fixtures/lock.json

**Comment by techyowl** [comment]
I'm using a nodejs dependency for communication with august api and am limited to the methods that has implemented currently.

**Comment by techyowl** [comment]
I opened an issue with the August-Connect repo. if there is a way to add the battery to that repo then Im sure we can find a way to add the battery to the locks in home bridge.

**Comment by dxdc** [comment]
Thanks @techyowl, makes sense! I haven't experimented directly with their API but will take a look myself at some point too and see what I can determine.

**Comment by techyowl** [comment]
I was able to get the battery status working however It is dependent on a PR Im about to push up to the august-connect repo.

**Comment by techyowl** [comment]
This is added in 5.0.7 with a fork of august-connect.
