### ISSUE TITLE
No able to disable notifications

### ISSUE THREAD

**Issue by Kepete** [techyowl/homebridge-august-smart-locks#20]
With other plugins and also with other accessories usually the lock(as the garage doors) have notifications. For some reason the lock added with this plugin did not show the notifications tab under accessory settings. 
All notifications were working, but I would like to disable these.

Is this really something a plugin can mandate? I used to think that it depends on accessory type, eg lock always has notifications. 

No notification settings:
![IMG_5975](https://user-images.githubusercontent.com/32489848/101981342-d3125900-3c74-11eb-9889-a292d3159e41.PNG)

Usually the notification settings
![IMG_5976](https://user-images.githubusercontent.com/32489848/101981312-95153500-3c74-11eb-9662-2acb8f00dd5f.PNG)

**Comment by techyowl** [comment]
I turn my lock notifications off per lock in the home settings under doors and locks. Not sure why it doesn't show up under the lock itself?

![image](https://user-images.githubusercontent.com/16109497/103453595-706b1680-4c90-11eb-9ced-f9e028494c24.png)

**Comment by techyowl** [comment]
Because it is actually possible to turn off these notifications and I cannot find out how to make the locks show up with the "Home Status" which would enable that submenu on the locks themselves. Im going to close this for now. Feel free to reopen this if you know how to enable that functionality.
