### ISSUE TITLE
Connection successful but locks not added

### ISSUE THREAD

**Issue by 3ne** [techyowl/homebridge-august-smart-locks#23]
HOOBS Version 3.3.1
Node version 14.15.1
AUGUST plugin version 5.0.6

Issue
New install of HOOBS and August Lock plugin. The retrieval of the locks are successful but then an an error occurs with the plugin. There are no accessories but HOOBS service continues to run. I have tried phone login as well with the same result.

N.B This all worked very well on the 5.0.3 version of the plugin. Once updated to the latest I noticed the username and password were shown in the logs as well.

1/5/2021, 7:29:24 PM - [AugustLocks] [August] getting locks ...
1/5/2021, 7:29:24 PM - [AugustLocks] [August] {
  apiKey: '*****-****-*****-*****-******',
  installID: '*****-*****-******-*******-****',
  password: '**********',
  IDType: 'email',
  augustID: '*******@********.com'
}
 code: '******'

1/5/2021, 7:29:30 PM - [AugustLocks] [August] Huggins Home Door A
1/5/2021, 7:29:30 PM - [AugustLocks] [August] LockId  ******
1/5/2021, 7:29:30 PM - [AugustLocks] [August] Huggins Home Door B
1/5/2021, 7:29:30 PM - [AugustLocks] [August] LockId  ******
1/5/2021, 7:29:30 PM - [AugustLocks] [August] Huggins Home Door C
1/5/2021, 7:29:30 PM - [AugustLocks] [August] LockId  *******
1/5/2021, 7:29:33 PM - [AugustLocks] [August] 0.08423927371586615
1/5/2021, 7:29:33 PM - (node:7143) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Service' of undefined
1/5/2021, 7:29:33 PM - at /home/hoobs/.hoobs/node_modules/homebridge-august-smart-locks/platform.js:450:40
1/5/2021, 7:29:33 PM - at processTicksAndRejections (internal/process/task_queues.js:93:5)
1/5/2021, 7:29:33 PM - (Use `node --trace-warnings ...` to show where the warning was created)
1/5/2021, 7:29:33 PM - (node:7143) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
1/5/2021, 7:29:33 PM - (node:7143) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
1/5/2021, 7:29:33 PM - [AugustLocks] [August] 0.47750721243210137
1/5/2021, 7:29:33 PM - (node:7143) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Service' of undefined
1/5/2021, 7:29:33 PM - at /home/hoobs/.hoobs/node_modules/homebridge-august-smart-locks/platform.js:450:40
1/5/2021, 7:29:33 PM - at processTicksAndRejections (internal/process/task_queues.js:93:5)
1/5/2021, 7:29:33 PM - (node:7143) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
1/5/2021, 7:29:34 PM - [AugustLocks] [August] 0.8775285427491326
1/5/2021, 7:29:34 PM - (node:7143) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Service' of undefined
1/5/2021, 7:29:34 PM - at /home/hoobs/.hoobs/node_modules/homebridge-august-smart-locks/platform.js:450:40
1/5/2021, 7:29:34 PM - at processTicksAndRejections (internal/process/task_queues.js:93:5)
1/5/2021, 7:29:34 PM - (node:7143) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by scottaki** [comment]
I’m seeing the same error:

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Service' of undefined

I have an August Wifi (latest, HomeKit capable), but want to use the API because the built-in HomeKit via Bluetooth is horrible.

Any suggestions appreciated!

**Comment by scottaki** [comment]
I haven’t had a chance to review the code in detail - sorry - but a quick question... should the third line here have this different structure?

`newAccessory.addService(self.Service.LockMechanism, thislockName);
newAccessory.addService(self.Service.ContactSensor, thislockName);
newAccessory.addService(this.Service.BatteryService); `

I’ll try and find a chance to answer this for myself if I can - but was something I noticed when first looked at the line called in the error.

**Comment by 3ne** [comment]
> I haven’t had a chance to review the code in detail - sorry - but a quick question... should the third line here have this different structure?
> 
> 
> 
> `newAccessory.addService(self.Service.LockMechanism, thislockName);
> 
> newAccessory.addService(self.Service.ContactSensor, thislockName);
> 
> newAccessory.addService(this.Service.BatteryService); `
> 
> 
> 
> I’ll try and find a chance to answer this for myself if I can - but was something I noticed when first looked at the line called in the error.

I think he was implementing reading the battery level. Not sure if he got it to work.

**Comment by 3ne** [comment]
> I’m seeing the same error:
> 
> 
> 
> UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Service' of undefined
> 
> 
> 
> I have an August Wifi (latest, HomeKit capable), but want to use the API because the built-in HomeKit via Bluetooth is horrible.
> 
> 
> 
> Any suggestions appreciated!

I have 2 HomeKit compatible and one non HomeKit August locks.

**Comment by scottaki** [comment]
@3ne – can confirm if the code (line 450 of platform.js) is updated from:

`newAccessory.addService(this.Service.BatteryService);`

...to

`newAccessory.addService(self.Service.BatteryService, thislockName);`

...the lock is added successfully. I get low battery warnings as my lock seems to report 0% battery always, but I was experiencing the same issue using the SmartThings platform, so don't think it's related to this code at all.

**Comment by 3ne** [comment]
> @3ne – can confirm if the code (line 450 of platform.js) is updated from:
> 
> 
> 
> `newAccessory.addService(this.Service.BatteryService);`
> 
> 
> 
> ...to
> 
> 
> 
> `newAccessory.addService(self.Service.BatteryService, thislockName);`
> 
> 
> 
> ...the lock is added successfully. I get low battery warnings as my lock seems to report 0% battery always, but I was experiencing the same issue using the SmartThings platform, so don't think it's related to this code at all.

Did the same and the log error is gone but the lock accessory isn't added.  I may need to start clean.

**Comment by scottaki** [comment]
Hmm ok. My lock didn't appear immediately after a reboot either – but it did after a minute or two. I thought it hadn't worked (but as you said, the error went), but then it magically appeared.

@techyowl Is it worth adding in something to capture 0% battery levels? I assume if the lock itself is responding but reporting 0%, it's an error (as it shouldn't be able to talk at 0%) – but how then you differentiate a real (very) low battery is another challenge.

**Comment by 3ne** [comment]
I updated the firmware on the locks themselves and the accessories showed up.

**Comment by techyowl** [comment]
> Hmm ok. My lock didn't appear immediately after a reboot either – but it did after a minute or two. I thought it hadn't worked (but as you said, the error went), but then it magically appeared.
> 
> 
> 
> @techyowl Is it worth adding in something to capture 0% battery levels? I assume if the lock itself is responding but reporting 0%, it's an error (as it shouldn't be able to talk at 0%) – but how then you differentiate a real (very) low battery is another challenge.

0% is theoretically possible since the api is handled via the august connect module. Is the lock that reports 0% the new built in WiFi model? That would mean that yes the lock isn't functioning properly and id contact august for a replacement within the first year of ownership.

**Comment by techyowl** [comment]
I added checks for 0% battery which now reports with no warning for low battery and will appear to be a normal battery level.

**Comment by techyowl** [comment]
Version 5.0.7 adds the fix you found for the battery service.

**Comment by acc552** [comment]
Hello, I have just installed this plugin, and was able to get everything configured and confirmed the setup was correct per the homebridge terminal page. However no lock shows up when adding to homekit (2nd gen lock). I do see the hub but no associated locks. Please note, that one lock is my parents house, the other is the onsite one within 15 ft of my homekit hub, not sure how much that matters, nor what the issue is I am having. any thoughts or suggestions would be apprecaited.
