### ISSUE TITLE
Repeatedly logging "[August] -1"

### ISSUE THREAD

**Issue by finder39** [techyowl/homebridge-august-smart-locks#26]
```
[1/7/2021, 17:42:36] [AugustLocks] [August] -1
[1/7/2021, 17:42:36] [AugustLocks] [August] -1
```

**Comment by finder39** [comment]
Looks to be related to battery. I'll make a pull request for this too

**Comment by techyowl** [comment]
New version just released.

**Comment by finder39** [comment]
I think you closed the wrong task on this. I added the pull request to my repo instead of yours by accident. Let me recreate it

**Comment by techyowl** [comment]
Sorry I totally did close the wrong task. Thanks for adding this PR it will be in the next release
