### ISSUE TITLE
Can I use this plugin to exposed the doorsense and not the lock?

### ISSUE THREAD

**Issue by thesquaremedia** [techyowl/homebridge-august-smart-locks#30]
Trying to expose the door open/close sensor to HomeKit for automations.

**Comment by 3ne** [comment]
This works for the non wifi models. My doorsense is shown as a contact sensor.

**Comment by thesquaremedia** [comment]
Yea I have the none wifi with connect. Can you take a screenshot of how the doorsense shows on HomeKit. Maybe I can hide the lock but let the sensor still show up.

**Comment by 3ne** [comment]
Sure.
![image](https://user-images.githubusercontent.com/4566763/105511217-486e4200-5c95-11eb-953d-fc43508e0f11.jpeg)
![image](https://user-images.githubusercontent.com/4566763/105511249-4f955000-5c95-11eb-9c15-daca478935d7.jpeg)
![image](https://user-images.githubusercontent.com/4566763/105511268-53c16d80-5c95-11eb-90d0-b72cd7f08f2b.jpeg)

**Comment by thesquaremedia** [comment]
ok yea, it definitely exposes it and it seems to work. it would be cool if I could just display that sensor without the lock. seems to me they would have to be added as two separate accessories. or maybe just a config setting to displayDoorSenseOnly

**Comment by techyowl** [comment]
Allowing the door sense sensors to be the only homekit devices shown goes against the main goal of this plugin. If you want to submit a PR that implements a switch behavior that is disabled by default for the configuration of this plugin and it meets to code standards. I have no issue reviewing it and merging it in as long as it does not interfere with the rest of the app functionality. (You will be expected to have thoroughly tested any code changes prior to me reviewing your PR)
