### ISSUE TITLE
Error code 1 - not sure what do to?

### ISSUE THREAD

**Issue by erictpeterson** [techyowl/homebridge-august-smart-locks#31]
CMD: npm install -g homebridge-august-smart-locks@latest

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/techyowl/august-connect.git
npm ERR! 
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! exited with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/erictpeterson/.npm/_logs/2021-01-25T01_34_05_445Z-debug.log

Command failed. Please review log for details.

**Comment by techyowl** [comment]
Your running homebridge on macos, google the xcrun error or follow homebridge installation guide for macos. This isn't an error with my repo it is an error with your homebridge installation.
