### ISSUE TITLE
Cannot Install on Ubuntu

### ISSUE THREAD

**Issue by p2kdev** [techyowl/homebridge-august-smart-locks#32]
admin@HP8300Ubuntu:/home/homebridge/.npm/_logs$ npm install -g homebridge-august-smart-locks
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/techyowl/august-connect.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/admin/.npm/_logs/2021-01-29T04_30_40_718Z-debug.log

**Comment by seannymurrs** [comment]
How did you solve this?
