### ISSUE TITLE
Separate icons (lock, door sense)

### ISSUE THREAD

**Issue by robhester** [techyowl/homebridge-august-smart-locks#36]
App works great on 4th gen (wifi) unit!  Within homekit, I am not able to separate the two functions -- lock and door sense -- so that they are presented separately on the home app.  This means that to lock/unlock one must click the lock, and then on the next screen, action the lock (to lock or unlock).  The native hk integration just presents the lock @ home level, so here we have one more step. Slightly trivial, but I thought to ask if this is something fixable in your addon.

Thanks!!

**Comment by techyowl** [comment]
I'm not sure how to implement what you are requesting. Anyone who is willing to work on this I am welcoming a PR for this.

**Comment by Beezwaad** [comment]
I also have Gen 4 WiFi but see two separate accessories within HomeKit.  The lock itself has a lock icon, the sensor can be configured to “Display As” a sensor/door/garage door/window.

**Comment by techyowl** [comment]
Ok then I will close this since it seems there isn't anything that needs to be done.
