### ISSUE TITLE
Could not communicate with August API

### ISSUE THREAD

**Issue by avion540** [techyowl/homebridge-august-smart-locks#37]
As of today, I am seeing a repeated error message in the logs: `Could not communicate with August API: getaddrinfo ENOTFOUND api-production.august.com`. Unlocking/locking through the Home app stills works.

**Comment by alexbaldwin** [comment]
Having the same error log here, but no locks are showing up after install.

**Comment by techyowl** [comment]
It seems that your dns is not able to resolve the domain api-production.august.com. Check your homebridge server's dns configuration and ensure no firewall is blocking that endpoint.
