### ISSUE TITLE
[August] Could not communicate with August API: GET failed with: 401

### ISSUE THREAD

**Issue by hansw1204** [techyowl/homebridge-august-smart-locks#41]
The other line is 
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
I have the 4th generation August lock and it won't connect to homekit either
Many thanks for any help.

**Comment by maeivi** [comment]
Getting the same error today. Tried getting a ned 2FA code, changing installation ID, but nothing works. August problem?

**Comment by maeivi** [comment]
Works fine after uninstalling and reinstalling.

**Comment by readybeginn** [comment]
I'm getting the same error with a new installation. None of the above solved it.

**Comment by techyowl** [comment]
Please follow the setup instructions carefully. If you don't get it after following them exactly it is quite possible august banned your ip and the more you use the plugin after a ban the longer the ban will be. uninstall the plugin and try it again in a few weeks.
