### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by seannymurrs** [techyowl/homebridge-august-smart-locks#42]
I’m getting the following error when trying to install the plugin. 

```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/techyowl/august-connect.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-02-27T17_47_22_955Z-debug.log
```

**Comment by RichDias** [comment]
I have the same error.  I can get around it by running
sudo npm install -g homebridge-august-smart-locks
but it hangs before install

**Comment by Greminn** [comment]
Hmm - same here. Either via the web interface or via cmd.

**Comment by Greminn** [comment]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/techyowl/august-connect.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm-cache\_logs\2021-04-03T22_38_00_600Z-debug.log

Command failed. Please review log for details.

**Comment by Greminn** [comment]
I had to install git, then it worked for me
