### ISSUE TITLE
August Smart Lock Gen 4

### ISSUE THREAD

**Issue by fcmarriott** [techyowl/homebridge-august-smart-locks#43]
I have installed an August Smart Lock Gen 4 / Wifi version. I attached the August Lock on my wifi network (no August bridge), and can see it in my IP address list. I was having trouble with the native Homekit configuration (No Response error all the time), so I added this Plugin to Homebridge.
First, I can confirm that the plugin works with the August Smart Lock Gen 4 / Wifi version (lock firmware 1.1.10). Homebridge version 1.3.3.

When using the August app, the lock / unlock command works nearly immediately, both on bluetooth as well as wifi. When using this plugin, in the Home app, the Unlock command takes 3-4 seconds, on average. The Lock command takes 11-12 seconds, on average. 

My Config JSON is : 
```
        {
            "name": "AugustLocks",
            "email": "fcxxxxxxxx@gmail.com",
            "password": "password",
            "code": "111111",
            "installId": "sameaspassword",
            "longPoll": 1,
            "shortPoll": 1,
            "platform": "AugustLocks"
        }
```

Sample Logs : 
```
[12/03/2021, 13:13:36] [AugustLocks] [August Front Door Lock] State was successfully set to unlock
[12/03/2021, 13:16:15] [AugustLocks] [August Front Door Lock] State was successfully set to lock
```

Is there anything I can do to help test or improve (not a dev).

**Comment by dxdc** [comment]
@fcmarriott

I would suggest testing 2 different things:

1. Run a speed test from the terminal on your HB device
2. Try the same experiment as the one you just ran, except turn off bluetooth and wifi on your phone first. This will force the August app to connect in the same way it does via the server, which may be a more realistic example of how the plugin is working.

The plugin connects to the August API whereas the August app (when connected to your home Wifi/bluetooth) connects directly to the lock.

**Comment by techyowl** [comment]
Closing due to this being dormant.
