### ISSUE TITLE
Door sense switch 

### ISSUE THREAD

**Issue by d2ustin** [techyowl/homebridge-august-smart-locks#46]
I was wondering if it’s possible to enable a switch if the door is open or closed not just locked, for example, if you have door sense installed, the august app will show if the door is open or closed as well. The switch would just be used as a switch for automations. 

Thanks!

**Comment by 3ne** [comment]
The door sense can already be used as a trigger for automations in Home.
![image](https://user-images.githubusercontent.com/4566763/114779615-f2f97c80-9d3b-11eb-8c0d-f736cc0e5031.jpeg)
![image](https://user-images.githubusercontent.com/4566763/114779631-f856c700-9d3b-11eb-8e0d-8abb497c56a0.jpeg)
![image](https://user-images.githubusercontent.com/4566763/114779649-fc82e480-9d3b-11eb-9448-ec4902c41b4b.jpeg)
