### ISSUE TITLE
Unable to install plugin - see error messaging

### ISSUE THREAD

**Issue by dougeoffrey** [techyowl/homebridge-august-smart-locks#50]
I've been attempting to install the plugin, but have been unsuccessful—seeing the attached error messages.

Any help to get this installed would be greatly appreciated.

[2021-05-01T17_08_29_866Z-debug.log](https://github.com/techyowl/homebridge-august-smart-locks/files/6410026/2021-05-01T17_08_29_866Z-debug.log)

![Screen Shot 2021-05-01 at 10 05 52 AM](https://user-images.githubusercontent.com/83511212/116790055-33106d00-aa67-11eb-8359-cb763d82f8c7.png)

**Comment by greyhoundguy** [comment]
You have to install Xcode. Terminal command:

xcode-select --install
