### ISSUE TITLE
Error in installing plugin

### ISSUE THREAD

**Issue by rabbadabba** [techyowl/homebridge-august-smart-locks#51]
Hi, am getting the following error when trying to install plugin.   Any help would be appreciated.
![image](https://user-images.githubusercontent.com/83954995/117647780-8ad67300-b1e1-11eb-8b7b-a6cf9ad31293.png)
[2021-05-10T10_41_40_480Z-debug.log](https://github.com/techyowl/homebridge-august-smart-locks/files/6451477/2021-05-10T10_41_40_480Z-debug.log)

**Comment by jmjones88** [comment]
@rabbadabba Just in case you haven't solved this - your platform is missing [git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git). Looks like your on Windows so may need to execute that in Git Bash.

I had this happen on my Raspberry Pi running homebridge. I did `sudo apt install git` and fixed it up for me and it installed right up.

**Comment by techyowl** [comment]
I dropped the git dependency in latest version try to update to 5.1.0
