### ISSUE TITLE
Error in Hoobs: characteristic value expected valid finite number and received "undefined" (undefined)

### ISSUE THREAD

**Issue by marcus-birju-sr** [techyowl/homebridge-august-smart-locks#56]
Plugin works as expected in HomeKit however HOOBS logs are showing this error:

`[August Smart Locks Bridge 14BF@August Front Door@Front Door@Lock Target State] characteristic value expected valid finite number and received "undefined" (undefined)`

It logs it every 10-15 seconds. I just updated to the latest version of HOOBS which allows the use of a virtual bridge to run the plugin on, not sure if that is related. The state above in the error is the [Bridge Name and ID@August Device Name@HomeKit Device Name]

Running:
Plugin v5.0.9
HOOBS v4.0.100
Node v14.17.5
Raspberry Pi 3+B - Buster

**Comment by EarmarkedHuman** [comment]
I'm having this exact same issue. Is there a resolution posted anywhere for this? I've looked and found none. Thanks!

**Comment by austinrdennis** [comment]
I'm also experiencing this, but with more symptoms. I get three distinct error messages repeatedly in the log. The thing is, it works, albeit slowly, but it works 95% of the time. Here's what I see:

August Smart Locks BridgeERROR[August Smart Locks Bridge E428@August Front Door@Front Door@Lock Target State] SET handler returned write response value, though the characteristic doesn't support write response

[August Smart Locks Bridge E428@August Front Door@Front Door@Lock Target State] characteristic value expected valid finite number and received "undefined" (undefined)

[August Smart Locks Bridge E428@Lock Target State] The write handler for the characteristic 'Lock Target State' on the accessory 'August Front Door' was slow to respond!

**Comment by cstromme** [comment]
I'm having the same issue here.

**Comment by austinrdennis** [comment]
Looks like an existing pull request fixes this issue. @techyowl request you merge the pull request.

**Comment by techyowl** [comment]
Thanks for the ping it is merged and now is live on npm as 5.1.0 along with a drop of the github dependency. I just decided to use my fork of august-connect under a new package name of august-connect-api. I cannot test it though as I don't have any august locks setup currently.

**Comment by austinrdennis** [comment]
@techyowl I can test this stuff with my Gun 3 lock and Raspberry Pi Hoobs
