### ISSUE TITLE
Question about homekit

### ISSUE THREAD

**Issue by Gragorg** [techyowl/homebridge-august-smart-locks#58]
I am looking at the Yale Assure powered by august lock.  My understanding is I need the august module in the lock to use features like auto unlock.  However I use homekit for smarthome automation.  Will this allow the Yale assure with the august model to be pulled into homebridge so I can use the lock status to trigger other events?

**Comment by 3ne** [comment]
Yes it will

**Comment by Gragorg** [comment]
Thanks!
